### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/mis-builder-contrib#30]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] mis_builder_analytic - By @peluko00 - #49
- [x] mis_builder_budget_product - By @dzungtran89 - #36
- [ ] mis_builder_total_committed_purchase

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by dzungtran89** [comment]
- mis_builder_total_committed_purchase: WIP

**Comment by dzungtran89** [comment]
- mis_builder_budget_product: https://github.com/OCA/mis-builder-contrib/pull/36

**Comment by peluko00** [comment]
- [mis_builder_analytic] https://github.com/OCA/mis-builder-contrib/pull/49
